services:
  mongo:
    image: mongo:7.0.5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
    deploy:
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 128mb
volumes:
  mongo-data:
    driver: local
