version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:8.12.2
    deploy:
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 128mb
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    image: kibana:8.12.2
    ports:
      - 5601:5601