services:
  elasticsearch:
    image: elasticsearch:8.12.2
    restart: always
    deploy:
      resources:
        limits:
          memory: 1gb
        reservations:
          memory: 128mb
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch-data:/usr/share/elasticsearch/data"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    image: kibana:8.12.2
    restart: always
    ports:
      - "5601:5601"
volumes:
  elasticsearch-data:
    driver: local
